version: '3.7'
services:
  # db server
  chat-mysql:
    image: mysql:5.7
    container_name: chat-mysql
    build: ./mysql/
    volumes:
      - ./mysql/data:/var/lib/mysql # データの永続化
      - ./mysql/sqls:/docker-entrypoint-initdb.d # 初期化時に実行するSQL
    environment:
      - MYSQL_ROOT_PASSWORD=osamura # パスワードはお好みで
      - TZ=Asis/Tokyo

  # API esrver
  chat-api:
    container_name: chat-api
    volumes:
      - ./:/app
    env_file:
      - ./.env
    environment:
      - FLASK_APP=/app/chat/run.py 
      - ENV GoogleMapAPIKEY
      - ENV YOUR_CHANNEL_ACCESS_TOKEN
      - ENV YOUR_CHANNEL_SECRET
    stdin_open: true
    tty: true
    build: ./chat
    command: /bin/bash
    ports:
      - 4000:4000
    depends_on:
      - chat-mysql