version: '3.7'
services:
  # db server
  chat-mysql-dev:
    container_name: chat-mysql-dev
    ports:
      - 4306:3306
    build:
      context: ./mysql
      dockerfile: Dockerfile.dev
    volumes:
      - ./mysql/data:/var/lib/mysql # データの永続化
      - ./mysql/sqls-dev:/docker-entrypoint-initdb.d # 初期化時に実行するSQL
    environment:
      - MYSQL_ROOT_PASSWORD=Mitsuya90
      - DB_PASSWORD=Mitsuya90
      - DB_DATABASE=dev
      - DB_TEST_PASSWORD=Mitsuya90
      - DB_TEST_DATABASE=test_chat
      - TZ=Asis/Tokyo

  # API esrver
  chat-api-dev:
    container_name: chat-api-dev
    volumes:
      - ./app:/app/
    ports:
      - 4000:4000
    env_file:
      - ./.env
    environment:
      TZ: "Asia/Tokyo"
      FLASK_APP: /app/src/server/run.py 
      ENV: GoogleMapAPIKEY
      ENV: YOUR_CHANNEL_ACCESS_TOKEN
      ENV: YOUR_CHANNEL_SECRET
      ENV: development
    stdin_open: true
    tty: true
    # command: flask run -h 0.0.0.0 -p 4000
    build:
      context: ./app
      dockerfile: Dockerfile.dev
