version: '3.7'
services:
  # db server
  chat-mysql:
    container_name: chat-mysql
    build: ./mysql/
    volumes:
      - ./mysql/data:/var/lib/mysql # データの永続化
      - ./mysql/sqls:/docker-entrypoint-initdb.d # 初期化時に実行するSQL
    environment:
      - MYSQL_ROOT_PASSWORD=osamura # パスワードはお好みで
      - TZ=Asis/Tokyo

  # API esrver
  chat-api:
    container_name: chat-api
    volumes:
      - ./:/app
    env_file:
      - ./.env
    environment:
      - FLASK_APP=/app/chat/run.py 
      - ENV GoogleMapAPIKEY
      - ENV YOUR_CHANNEL_ACCESS_TOKEN
      - ENV YOUR_CHANNEL_SECRET
    stdin_open: true
    tty: true
    ports:
      - 4000:4000
    build: ./chat
    # command: /bin/bash
    command: flask db init
    command: flask db migrate
    command: flask db upgrade
    command: flask run -h 0.0.0.0 -p 4000