version: '3.7'
services:
  # db server
  chat-mysql-dev:
    container_name: chat-mysql-dev
    ports:
      - 4306:3306
    build:
      context: ./mysql
      dockerfile: Dockerfile.dev
    volumes:
      - ./mysql/data:/var/lib/mysql # データの永続化
      - ./mysql/sqls:/docker-entrypoint-initdb.d # 初期化時に実行するSQL
    env_file:
      - ./.env
    environment:
      TZ: Asis/Tokyo
      ENV: MYSQL_ROOT_PASSWORD
      ENV: DB_PASSWORD
      ENV: DB_DATABASE
      ENV: DB_TEST_PASSWORD
      ENV: DB_TEST_DATABASE

  # API esrver
  chat-api-dev:
    container_name: chat-api-dev
    volumes:
      - ./app:/app/
    ports:
      - 4000:4000
    env_file:
      - ./.env
    environment:
      TZ: "Asia/Tokyo"
      FLASK_APP: /app/src/server/run.py 
      ENV: GoogleMapAPIKEY
      ENV: YOUR_CHANNEL_ACCESS_TOKEN
      ENV: YOUR_CHANNEL_SECRET
      ENV: development
    stdin_open: true
    tty: true
    # command: flask run -h 0.0.0.0 -p 4000
    build:
      context: ./app
      dockerfile: Dockerfile.dev
