"""empty message

Revision ID: 4f65b6b9eed3
Revises: 
Create Date: 2019-10-10 15:49:46.426871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f65b6b9eed3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ask_now', sa.Boolean(), nullable=False),
    sa.Column('visit_time', sa.DateTime(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(length=255), nullable=False),
    sa.Column('prefer', sa.String(length=255), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=False),
    sa.Column('inquiry', sa.String(length=255), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('updateTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
