FROM python:3.6

RUN apt-get update


# workdirの指定
WORKDIR /var/www

# 依存Pythonライブラリ一覧コピー
COPY Pipfile /var/www
COPY Pipfile.lock /var/www

# install pipenv
RUN pip install -U pip && \
    pip install pipenv && \
    pipenv install --dev --system

# workdirの指定
WORKDIR /var/www/src
