FROM python:3.6

RUN apt-get update


# workdirの指定
WORKDIR /app

# 依存Pythonライブラリ一覧コピー
COPY Pipfile /app
COPY Pipfile.lock /app

# install pipenv
RUN pip install -U pip && \
    pip install pipenv && \
    pipenv install --dev --system

# workdirの指定
WORKDIR /app/src

# command: flask run -h 0.0.0.0 -p 4000
CMD ["flask","run","-h", "0.0.0.0", "-p", "4000"]
